/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package servicio_mensajeria;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author pc
 */
public class Estudiantes extends javax.swing.JFrame {

    /**
     * Creates new form Estudiantes
     */
    public Estudiantes() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Tablero del Estudiante.");
        
        ImageIcon imag_1 = new ImageIcon("src/images/banner_bandera.png");
        
        ImageIcon imag_2 = new ImageIcon("src/images/banner_azulrey.png");
        
        ImageIcon imag_3 = new ImageIcon("src/images/raya_marino.png");
        
        ImageIcon imag_4 = new ImageIcon("src/images/banner_blancp.png");
        
        ImageIcon imag_5 = new ImageIcon("src/images/cartel.png");
        
        Icon ic_1 = new ImageIcon(imag_1.getImage().getScaledInstance(jLabel_blanco.getWidth(),
                jLabel_blanco.getHeight(), Image.SCALE_DEFAULT));
        
        Icon ic_2 = new ImageIcon(imag_2.getImage().getScaledInstance(jLabel_azulrey.getWidth(),
                jLabel_azulrey.getHeight(), Image.SCALE_DEFAULT));
        
        Icon ic_3 = new ImageIcon(imag_3.getImage().getScaledInstance(jLabel_marina.getWidth(),
                jLabel_marina.getHeight(), Image.SCALE_DEFAULT));
        
        Icon ic_4 = new ImageIcon(imag_4.getImage().getScaledInstance(jLabel_raya.getWidth(),
                jLabel_raya.getHeight(), Image.SCALE_DEFAULT));
        
        Icon ic_5 = new ImageIcon(imag_5.getImage().getScaledInstance(jLabel_cartel.getWidth(),
                jLabel_cartel.getHeight(), Image.SCALE_DEFAULT));
        
        jLabel_blanco.setIcon(ic_1);
        jLabel_azulrey.setIcon(ic_2);
        jLabel_marina.setIcon(ic_3);
        jLabel_raya.setIcon(ic_4);
        jLabel_cartel.setIcon(ic_5);
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel_azulrey = new javax.swing.JLabel();
        jLabel_cartel = new javax.swing.JLabel();
        jLabel_marina = new javax.swing.JLabel();
        jLabel_blanco = new javax.swing.JLabel();
        jLabel_raya = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voto_est.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, 120));

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel5.setText("LOS ESTUDIANTES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 95, -1, -1));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel1.setText("CONSULTA DE INFORMACION PARA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONSULTAR PUESTO DE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 225, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VOTACIÓN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 245, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IRREGULARIDADES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 415, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/estudiante.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 150, 120));
        getContentPane().add(jLabel_azulrey, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 270, 705));
        getContentPane().add(jLabel_cartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 140));
        getContentPane().add(jLabel_marina, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 270, 80));
        getContentPane().add(jLabel_blanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 830, 780));
        getContentPane().add(jLabel_raya, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 10, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        new Registrar_Estudiante().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        new Irregularidades().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_azulrey;
    private javax.swing.JLabel jLabel_blanco;
    private javax.swing.JLabel jLabel_cartel;
    private javax.swing.JLabel jLabel_marina;
    private javax.swing.JLabel jLabel_raya;
    // End of variables declaration//GEN-END:variables
}
