
package servicio_mensajeria;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;



public class Interfaz_Votar extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Votar
     */
    public Interfaz_Votar() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Tablero de organizadores.");
        
        ImageIcon imag_1 = new ImageIcon("src/images/banner_bandera.png");
        
        ImageIcon imag_2 = new ImageIcon("src/images/banner_azulrey.png");
        
        ImageIcon imag_3 = new ImageIcon("src/images/raya_marino.png");
        
        ImageIcon imag_4 = new ImageIcon("src/images/banner_blancp.png");
        
        ImageIcon imag_5 = new ImageIcon("src/images/cartel.png");
        
        Icon ic_1 = new ImageIcon(imag_1.getImage().getScaledInstance(jLabel_blanco.getWidth(),
                jLabel_blanco.getHeight(), Image.SCALE_DEFAULT));
        
        Icon ic_2 = new ImageIcon(imag_2.getImage().getScaledInstance(jLabel_azulrey.getWidth(),
                jLabel_azulrey.getHeight(), Image.SCALE_DEFAULT));
        
        Icon ic_3 = new ImageIcon(imag_3.getImage().getScaledInstance(jLabel_marina.getWidth(),
                jLabel_marina.getHeight(), Image.SCALE_DEFAULT));
        
        Icon ic_4 = new ImageIcon(imag_4.getImage().getScaledInstance(jLabel_raya.getWidth(),
                jLabel_raya.getHeight(), Image.SCALE_DEFAULT));
        
        Icon ic_5 = new ImageIcon(imag_5.getImage().getScaledInstance(jLabel_cartel.getWidth(),
                jLabel_cartel.getHeight(), Image.SCALE_DEFAULT));
        
        
        jLabel_blanco.setIcon(ic_1);
        jLabel_azulrey.setIcon(ic_2);
        jLabel_marina.setIcon(ic_3);
        jLabel_raya.setIcon(ic_4);
        jLabel_cartel.setIcon(ic_5);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_raya = new javax.swing.JLabel();
        jLabel_blanco = new javax.swing.JLabel();
        jLabel_azulrey = new javax.swing.JLabel();
        jLabel_cartel = new javax.swing.JLabel();
        jLabel_marina = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jurados.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 150, 120));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/votos.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 150, 120));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/irregular.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 150, 120));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/votantes.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, 120));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("IRREGULARIDADES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 735, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONSULTAR NUMERO DE VOTOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 564, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JURADOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 395, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VOTANTES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 225, -1, -1));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel1.setText("PANEL DE GESTIÓN DEL ORGANIZADOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));
        getContentPane().add(jLabel_raya, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 10, 780));
        getContentPane().add(jLabel_blanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 830, 780));
        getContentPane().add(jLabel_azulrey, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 270, 705));
        getContentPane().add(jLabel_cartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 140));
        getContentPane().add(jLabel_marina, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 270, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        new Tabla_jurados().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        new Consultar_Votos().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        new Irr_Organizador().setVisible(true);

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        new Tabla_votantes().setVisible(true);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Votar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Votar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Votar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Votar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Votar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_azulrey;
    private javax.swing.JLabel jLabel_blanco;
    private javax.swing.JLabel jLabel_cartel;
    private javax.swing.JLabel jLabel_marina;
    private javax.swing.JLabel jLabel_raya;
    // End of variables declaration//GEN-END:variables
}
