/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package servicio_mensajeria;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

import java.sql.*;
import classes.get_connection;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Login extends javax.swing.JFrame {

    private String user_login;
    private String pass_login;
    public static String user_name;
    public static String estatus_login;

    

    public Login() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Inicio de Sesión.");

        ImageIcon imag_1 = new ImageIcon("src/images/Bandera_Juan.png");

        ImageIcon imag_2 = new ImageIcon("src/images/Icono_vota2.png");

        ImageIcon imag_3 = new ImageIcon("src/images/banner.png");

        ImageIcon imag_4 = new ImageIcon("src/images/banner_blancp.png");

        Icon ic_1 = new ImageIcon(imag_1.getImage().getScaledInstance(jLabel_wallpaper.getWidth(),
                jLabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));

        Icon ic_2 = new ImageIcon(imag_2.getImage().getScaledInstance(jLabel_voteIcon.getWidth(),
                jLabel_voteIcon.getHeight(), Image.SCALE_DEFAULT));

        Icon ic_3 = new ImageIcon(imag_3.getImage().getScaledInstance(jLabel_banner.getWidth(),
                jLabel_banner.getHeight(), Image.SCALE_DEFAULT));

        Icon ic_4 = new ImageIcon(imag_4.getImage().getScaledInstance(jLabel_whiteLine.getWidth(),
                jLabel_whiteLine.getHeight(), Image.SCALE_DEFAULT));

        jLabel_wallpaper.setIcon(ic_1);
        jLabel_voteIcon.setIcon(ic_2);
        jLabel_banner.setIcon(ic_3);
        jLabel_whiteLine.setIcon(ic_4);

        repaint();
        
       
    
        
        
    }

    @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icono_vota2.png"));
        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jTextField_user = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel_whiteLine = new javax.swing.JLabel();
        jLabel_voteIcon = new javax.swing.JLabel();
        jLabel_banner = new javax.swing.JLabel();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INSTITUCION EDUCATIVA TECNICA - JUAN JOSE NIETO | Copyright ©");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 690, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 520, -1, -1));

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JUAN JOSE NIETO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, -1, -1));

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INSTITUCIÓN EDUCATIVA TECNICA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de votación ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 240, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, -1, -1));

        jPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 545, 180, -1));

        jTextField_user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_userActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 475, 180, -1));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("ACCEDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 590, -1, -1));

        jLabel_whiteLine.setText("jLabel7");
        getContentPane().add(jLabel_whiteLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 10, 740));
        getContentPane().add(jLabel_voteIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 190, 180));

        jLabel_banner.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jLabel_banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 270, 740));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_userActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        user_login = jTextField_user.getText().trim();
        pass_login = jPasswordField.getText().trim();

        try {

            Connection cn_1 = get_connection.connect();
            PreparedStatement pst = cn_1.prepareStatement(
                    "select nombre, estatus from usuarios where nombre_usuario = '" + user_login + "' and pass_usuario = '" + pass_login + "'");

            ResultSet rs_1 = pst.executeQuery();

            if (rs_1.next()) {

                estatus_login = rs_1.getString("estatus");
                
                user_name = rs_1.getString("nombre");

                if (estatus_login.equals("Organizador")) {

                    this.setVisible(false);
                    new Interfaz_Votar().setVisible(true);

                } else if (estatus_login.equals("Estudiante")) {

                    this.setVisible(false);
                    new Estudiantes().setVisible(true);

                } else if (estatus_login.equals("Jurado")) {

                    this.setVisible(false);
                    new jurados().setVisible(true);

                }

            } else {

                JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos, Verifique nuevamente", "Error", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {

            System.err.println("SQL ERROR! " + e);
            JOptionPane.showMessageDialog(null, "Error con la conexion a la base de datos, contacte al desarrollador", "ERROR!", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_banner;
    private javax.swing.JLabel jLabel_voteIcon;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JLabel jLabel_whiteLine;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_user;
    // End of variables declaration//GEN-END:variables

   
}
