/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package servicio_mensajeria;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

import classes.get_connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class Registrar_Estudiante extends javax.swing.JFrame {

    DefaultTableModel model_1 = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {

            return false;
        }

    };

    /**
     * Creates new form Registrar_Estudiante
     */
    public Registrar_Estudiante() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Registro de nuevo estudiante.");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon imag_1 = new ImageIcon("src/images/banner_azulrey.png");

        Icon ic_1 = new ImageIcon(imag_1.getImage().getScaledInstance(jLabel_wallpaper.getWidth(),
                jLabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));

        jLabel_wallpaper.setIcon(ic_1);

        repaint();

        try {

            Connection cn = get_connection.connect();
            PreparedStatement pst = cn.prepareStatement("select ID, nombre, nombre_usuario, estatus, mesa from usuarios where estatus = 'Estudiante'");

            jTable1 = new JTable(model_1);
            jScrollPane1.setViewportView(jTable1);

            model_1.addColumn("ID");
            model_1.addColumn("Nombre del Estudiante");
            model_1.addColumn("Nombre Usuario");
            model_1.addColumn("Estatus");
            model_1.addColumn("Mesa");

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                Object[] rw = new Object[5];

                for (int i = 0; i < 5; i++) {

                    rw[i] = rs.getObject(i + 1);

                }
                model_1.addRow(rw);

            }

        } catch (SQLException e) {
            System.err.println("SQL ERROR! " + e);
            JOptionPane.showMessageDialog(
                    null, "Error con la conexion a la base de datos, contacte al programador", "ERROR BASE DE DATOS!", JOptionPane.ERROR_MESSAGE);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_mesa = new javax.swing.JTextField();
        jTextField_pass = new javax.swing.JTextField();
        jTextField_usuario = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mesa:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre de Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROCESO DE REGISTRO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE ESTUDIANTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 610, 300));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("REGISTRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 680, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("ACTUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jTextField_mesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 615, 260, -1));

        jTextField_pass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 535, 260, -1));

        jTextField_usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 615, 260, -1));

        jTextField_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 535, 260, -1));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            Connection cn = get_connection.connect();
            PreparedStatement pst = cn.prepareStatement("select ID, nombre, nombre_usuario, estatus, mesa from usuarios where estatus = 'Estudiante'");

            model_1.setRowCount(0);

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                Object[] rw = new Object[5];

                for (int i = 0; i < 5; i++) {

                    rw[i] = rs.getObject(i + 1);

                }
                model_1.addRow(rw);

            }

        } catch (SQLException e) {

            System.err.println("SQL ERROR! " + e);
            JOptionPane.showMessageDialog(
                    null, "Error con la conexion a la base de datos, contacte al programador", "ERROR BASE DE DATOS!", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String name, usuario, password, mesa_string;

        int validacion = 0, mesa_int;

        name = jTextField_name.getText().trim();
        usuario = jTextField_usuario.getText().trim();
        password = jTextField_pass.getText().trim();

        mesa_string = jTextField_mesa.getText().trim();

        if (name.equals("")) {

            validacion++;

        }

        if (usuario.equals("")) {

            validacion++;

        }

        if (password.equals("")) {

            validacion++;

        }

        if (mesa_string.equals("")) {

            validacion++;

        }

        try {

            if (validacion == 0) {

                Connection cn_2 = get_connection.connect();

                PreparedStatement pst_2 = cn_2.prepareStatement("insert into usuarios values(?,?,?,?,?,?)");

                mesa_int = Integer.parseInt(mesa_string);

                pst_2.setInt(1, 0);
                pst_2.setString(2, name);
                pst_2.setString(3, usuario);
                pst_2.setString(4, password);
                pst_2.setString(5, "Estudiante");
                pst_2.setInt(6, mesa_int);

                pst_2.executeUpdate();
                cn_2.close();

                JOptionPane.showMessageDialog(null, "Estudiante registrado con exito!");

            } else {

                JOptionPane.showMessageDialog(
                        null, "Llene todo los campos requeridos.", "ERROR, FALTA DE DATOS!", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {

            System.err.println("SQL ERROR! " + e);
            JOptionPane.showMessageDialog(
                    null, "Error con la conexion a la base de datos, contacte al programador", "ERROR BASE DE DATOS!", JOptionPane.ERROR_MESSAGE);

        }

        try {

            if (validacion == 0) {

                Connection cn_3 = get_connection.connect();

                PreparedStatement pst_3 = cn_3.prepareStatement("insert into est_no_voto values(?,?,?,?)");

                mesa_int = Integer.parseInt(mesa_string);
                
                pst_3.setInt(1, 0);
                pst_3.setString(2, name);
                pst_3.setString(3, "Estudiante");
                pst_3.setInt(4, mesa_int);
                
                pst_3.executeUpdate();
                
                cn_3.close();
            }
            
        } catch (NumberFormatException | SQLException e) {
            
            System.err.println("SQL ERROR! " + e);
            JOptionPane.showMessageDialog(
                    null, "Error con la conexion a la base de datos, contacte al programador", "ERROR BASE DE DATOS!", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_Estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_mesa;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_pass;
    private javax.swing.JTextField jTextField_usuario;
    // End of variables declaration//GEN-END:variables
}
